### ISSUE TITLE
Credits to gamecord

### ISSUE THREAD

**Issue by rufy545** [Tomato6966/Multipurpose-discord-bot#21]
At least give credits to gamecord lmao and dont say you didnt steal it because in the 2048 command there is the api of the gamecord's owner lol

**Comment by K1ZANA** [comment]
Are you the owner, developer o. Staff member / anything that has something to do with GameCord, if no, its not your problem.

**Comment by Tomato6966** [comment]
I am/was commiting and contributing to gamecord
I am just using those on which i was working with them

Gamecord was stealing from weky-npm
I am was commiting and contributing to weky-npm

I am7was comminting and contributing to memer-api
I create the whole npm repository

**Comment by rufy545** [comment]
Gamecord was stealing from weky? Who asked that tbh. If gamecord is a copy of weky why are you using that lmao. I just wanna know

**Comment by Zakariagtse1** [comment]
> Gamecord was stealing from weky? Who asked that tbh. If gamecord is a copy of weky why are you using that lmao. I just wanna know. And yea you are pretty smart ngl, if you contribute to his package no one will be able to tell you anything anymore damn

is this even your problem to say?

**Comment by kWAYTV** [comment]
> Gamecord was stealing from weky? Who asked that tbh. If gamecord is a copy of weky why are you using that lmao. I just wanna know. And yea you are pretty smart ngl, if you contribute to his package no one will be able to tell you anything anymore damn

u dumb i can tell u

**Comment by rufy545** [comment]
Of course. He always wants credits but He doesnt give them lmao. How sad

**Comment by Lcxd65** [comment]
Damn how sad guys, he stole some games commands and you are trying to defend him dont put other shit he's on the wrong side, stop.

**Comment by DoraemonDpdx** [comment]
Tomato Is The Best Dev

**Comment by ZayNip** [comment]
> At least give credits to gamecord lmao and dont say you didnt steal it because in the 2048 command there is the api of the gamecord's owner lol

is this even your problem to say?

**Comment by Tomato6966** [comment]
> any

First. I am not using Gamecord
Second I am using the script of weky which i adjusted and pushed to Gamecord
There is no reason for me to Credit something which I was working on
![image](https://user-images.githubusercontent.com/68145571/151369583-696b9d45-becf-45dc-b2cd-ff79c49f3af8.png)
I've been working on several projects with aniket, yash etc. If i would use the GAMECORD npm package i would give them credits. but i'm not doing it. 

Since weky is about to shut down i asked to continue working on it, but they are unsure about that.

Imma soon change all game commands anyways

**Comment by Tomato6966** [comment]
To stop this conversation i closed this issue and will redit aniket not gamecord

**Comment by TrueWLAN** [comment]
ok
